### ISSUE TITLE
emacs indent angularjs code badly

### ISSUE THREAD

**Issue by islam-taha** [omouse/angularjs-mode#8]
It's really sad not to write well formatted angularJs code inside emacs, the image below shows what i'am saying. what is happening inside the photo is that the code is already well formatted as it is but when i create a new line it become like the photo says. If any one knows any solution to this problem, it would be so helpful to me. (note i've used angularJs mode but in vain).
<img width="379" alt="screen shot 2016-02-12 at 1 44 56 pm" src="https://cloud.githubusercontent.com/assets/11490365/13009056/d50141dc-d1a2-11e5-84ca-ba68b88a0475.png">

**Comment by omouse** [comment]
looks like an issue with javascript-mode (the mode we're deriving from for angularjs-mode)
